name: diesel_demo

services:
  postgres:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_DB=diesel_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisnotsecure
    ports:
      - "5435:5432"